### ISSUE TITLE
标准布隆过滤器报错

### ISSUE THREAD

**Issue by phpsxg** [01ly/bloompy#3]
# 1.使用标准布隆过滤器报错
## 代码如下：
```
import bloompy
bf = bloompy.BloomFilter(error_rate=0.001,element_num=10**3)
bf.add(1) 
```
## 报错如下：
```
Traceback (most recent call last):
  File "/home/turing/workspace/plato-schedule-manage/useless/bloompy_test.py", line 6, in <module>
    bf.add(1) 
  File "/usr/local/conda/lib/python3.8/site-packages/bloompy/__init__.py", line 116, in add
    if self._at_half_fill():
  File "/usr/local/conda/lib/python3.8/site-packages/bloompy/__init__.py", line 185, in _at_half_fill
    return self.bit_array.count()/self.bit_array.length()*1.0>=0.5
AttributeError: 'bitarray.bitarray' object has no attribute 'length'

```

# 2.从文件里恢复过滤器不起效

**Comment by 01ly** [comment]
应该是bitarray库的版本不一致



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年02月17日 11:26 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [01ly/bloompy] 标准布隆过滤器报错 (Issue #3) |

1.使用标准布隆过滤器报错
代码如下：
import bloompy

bf = bloompy.BloomFilter(error_rate=0.001,element_num=10**3)

bf.add(1) 


报错如下：
Traceback (most recent call last):

  File "/home/turing/workspace/plato-schedule-manage/useless/bloompy_test.py", line 6, in <module>

    bf.add(1) 

  File "/usr/local/conda/lib/python3.8/site-packages/bloompy/__init__.py", line 116, in add

    if self._at_half_fill():

  File "/usr/local/conda/lib/python3.8/site-packages/bloompy/__init__.py", line 185, in _at_half_fill

    return self.bit_array.count()/self.bit_array.length()*1.0>=0.5

AttributeError: 'bitarray.bitarray' object has no attribute 'length'




2.从文件里恢复过滤器不起效

**Comment by phpsxg** [comment]
> 应该是bitarray库的版本不一致 | | ***@***.*** | | ***@***.*** |
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2022年02月17日 11:26 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***> | | 主题 | [01ly/bloompy] 标准布隆过滤器报错 (Issue #3) | 1.使用标准布隆过滤器报错 代码如下： import bloompy bf = bloompy.BloomFilter(error_rate=0.001,element_num=10**3) bf.add(1) 报错如下： Traceback (most recent call last): File "/home/turing/workspace/plato-schedule-manage/useless/bloompy_test.py", line 6, in <module> bf.add(1) File "/usr/local/conda/lib/python3.8/site-packages/bloompy/__init__.py", line 116, in add if self._at_half_fill(): File "/usr/local/conda/lib/python3.8/site-packages/bloompy/__init__.py", line 185, in _at_half_fill return self.bit_array.count()/self.bit_array.length()*1.0>=0.5 AttributeError: 'bitarray.bitarray' object has no attribute 'length' 2.从文件里恢复过滤器不起效 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

目前使用的是bitarray==2.3.0，应该安装哪个版本？
```
bitarray                           2.3.0
bloompy                            0.1.1
pybloom-live                       3.1.0
```

**Comment by wcx-1** [comment]
直接改bloompy的源码吧，那个报错说没有length这个属性，就是说.length()方法不能用，那就直接换成len()。综上，把报错的那一行源码里的self.bit_array.length()改成len(self.bit_array)，经测试已通过。

**Comment by wcx-1** [comment]
我看了一眼源码，应该不只标准布隆会报错，标准扩容布隆也会报错，因为标准扩容布隆调用了标准布隆，但是计数的那俩布隆没这个问题
